blueprint:
  name: Menstrual Cycle Tracker - Notifications
  description: >
    Send notifications for cycle events: period due soon, period started/ended,
    fertile window, PMS window, and ovulation phase. Each notification type can
    be individually enabled or disabled.

    Set the subject and possessive fields to personalise messages for yourself
    or someone else — e.g. "You / Your" (default), "Alex / Alex's", or
    "They / Their".
  domain: automation
  input:

    # ── Entities ─────────────────────────────────────────────────────────────
    period_active_sensor:
      name: Period Active (Binary Sensor)
      description: "binary_sensor.[name]_period_active"
      selector:
        entity:
          domain: binary_sensor

    next_period_sensor:
      name: Next Period (Sensor)
      description: "sensor.[name]_next_period — must have days_until_next_period attribute"
      selector:
        entity:
          domain: sensor

    fertile_window_sensor:
      name: Fertile Window (Sensor)
      description: "sensor.[name]_fertile_window"
      selector:
        entity:
          domain: sensor

    current_phase_sensor:
      name: Current Phase (Sensor)
      description: "sensor.[name]_current_phase"
      selector:
        entity:
          domain: sensor

    # ── Notification service ──────────────────────────────────────────────────
    notify_service:
      name: Notification Service
      description: >
        The service to call for notifications, e.g. notify.mobile_app_my_phone
        or notify.notify for the default service.
      default: notify.notify
      selector:
        text:

    # ── Pronouns / name ───────────────────────────────────────────────────────
    name_subject:
      name: Subject (who the tracker is for)
      description: >
        Used as the subject in notification messages.
        Examples: "You", "Alex", "She", "He", "They"
      default: "You"
      selector:
        text:

    name_possessive:
      name: Possessive (who the tracker belongs to)
      description: >
        Used as the possessive in notification messages.
        Examples: "Your", "Alex's", "Her", "His", "Their"
      default: "Your"
      selector:
        text:

    # ── Daily check time ──────────────────────────────────────────────────────
    daily_check_time:
      name: Daily Check Time
      description: Time each day to check for upcoming period / PMS window.
      default: "08:00:00"
      selector:
        time:

    # ── Period due soon ───────────────────────────────────────────────────────
    enable_period_due:
      name: Notify — Period Due Soon
      description: Send a notification when the period is predicted N days away.
      default: true
      selector:
        boolean:

    period_warning_days:
      name: Period Warning (Days Before)
      description: How many days before the predicted period to send the alert.
      default: 2
      selector:
        number:
          min: 1
          max: 7
          unit_of_measurement: days

    # ── Period started ────────────────────────────────────────────────────────
    enable_period_started:
      name: Notify — Period Started
      description: Send a notification when the period active sensor turns on.
      default: true
      selector:
        boolean:

    # ── Period ended ──────────────────────────────────────────────────────────
    enable_period_ended:
      name: Notify — Period Ended
      description: Send a notification when the period active sensor turns off.
      default: true
      selector:
        boolean:

    # ── Fertile window ────────────────────────────────────────────────────────
    enable_fertile_window:
      name: Notify — Fertile Window Started
      description: Send a notification when the fertile window begins.
      default: true
      selector:
        boolean:

    # ── PMS window ────────────────────────────────────────────────────────────
    enable_pms_window:
      name: Notify — PMS Window
      description: Send a daily notification during the 5-day PMS window.
      default: true
      selector:
        boolean:

    # ── Ovulation phase ───────────────────────────────────────────────────────
    enable_ovulation:
      name: Notify — Ovulation Phase Started
      description: Send a notification when the current phase changes to Ovulation.
      default: false
      selector:
        boolean:

    # ── Period start reminder ─────────────────────────────────────────────────
    enable_period_reminder:
      name: Notify — Period Start Reminder (Confirmable)
      description: >
        On the predicted period start day, send a notification with a
        "Log it now" button. Repeats daily until the period is logged.
      default: true
      selector:
        boolean:

    period_reminder_action_id:
      name: Period Reminder Action ID
      description: >
        A unique identifier for the "Log it now" button action. Must be
        different for each automation using this blueprint (e.g. if you have
        two trackers, use "LOG_PERIOD_ALEX" and "LOG_PERIOD_JORDAN").
      default: "LOG_PERIOD_STARTED"
      selector:
        text:

    tracker_for_service:
      name: Tracker (for action button)
      description: >
        Leave empty if you only have one tracker. For multiple trackers,
        enter the tracker name (e.g. "Alex") so the button logs to the
        correct person.
      default: ""
      selector:
        text:


# ── Triggers ──────────────────────────────────────────────────────────────────
trigger:

  # Period started
  - platform: state
    entity_id: !input period_active_sensor
    to: "on"
    id: period_started

  # Period ended
  - platform: state
    entity_id: !input period_active_sensor
    to: "off"
    id: period_ended

  # Fertile window began
  - platform: state
    entity_id: !input fertile_window_sensor
    to: "Yes"
    id: fertile_window

  # Ovulation phase
  - platform: state
    entity_id: !input current_phase_sensor
    to: "Ovulation"
    id: ovulation

  # Daily check (period due soon + PMS window + overdue reminder)
  - platform: time
    at: !input daily_check_time
    id: daily_check

  # "Log it now" button tapped on the period start reminder notification
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: !input period_reminder_action_id
    id: period_start_confirmed


# ── Variables ─────────────────────────────────────────────────────────────────
variables:
  period_active_sensor: !input period_active_sensor
  next_period_sensor: !input next_period_sensor
  fertile_window_sensor: !input fertile_window_sensor
  current_phase_sensor: !input current_phase_sensor
  notify_service: !input notify_service
  name_subject: !input name_subject
  name_possessive: !input name_possessive
  period_warning_days: !input period_warning_days
  enable_period_due: !input enable_period_due
  enable_period_started: !input enable_period_started
  enable_period_ended: !input enable_period_ended
  enable_fertile_window: !input enable_fertile_window
  enable_pms_window: !input enable_pms_window
  enable_ovulation: !input enable_ovulation
  enable_period_reminder: !input enable_period_reminder
  period_reminder_action_id: !input period_reminder_action_id
  tracker_for_service: !input tracker_for_service
  days_until: >
    {{ state_attr(next_period_sensor, 'days_until_next_period') | int(-1) }}
  days_overdue: >
    {{ state_attr(next_period_sensor, 'days_overdue') | int(-1) }}


# ── Actions ───────────────────────────────────────────────────────────────────
action:
  - choose:

      # ── Period started ──────────────────────────────────────────────────────
      - conditions:
          - condition: trigger
            id: period_started
          - condition: template
            value_template: "{{ enable_period_started }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "{{ name_possessive }} Period Started"
              message: >
                {{ name_possessive }} period has started today. 💙

      # ── Period ended ────────────────────────────────────────────────────────
      - conditions:
          - condition: trigger
            id: period_ended
          - condition: template
            value_template: "{{ enable_period_ended }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "{{ name_possessive }} Period Ended"
              message: >
                {{ name_possessive }} period has ended.
                Next period predicted: {{ states(next_period_sensor) }}.

      # ── Fertile window ──────────────────────────────────────────────────────
      - conditions:
          - condition: trigger
            id: fertile_window
          - condition: template
            value_template: "{{ enable_fertile_window }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "Fertile Window"
              message: >
                {{ name_subject }} {{ "have" if name_subject in ["You", "They", "We"] else "has" }}
                entered {{ name_possessive | lower }} fertile window today.

      # ── Ovulation phase ─────────────────────────────────────────────────────
      - conditions:
          - condition: trigger
            id: ovulation
          - condition: template
            value_template: "{{ enable_ovulation }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "Ovulation Phase"
              message: >
                {{ name_possessive }} cycle has entered the Ovulation phase.

      # ── Daily check: period due soon + PMS window ──────────────────────────
      # Both checks run independently so both can fire on the same day.
      - conditions:
          - condition: trigger
            id: daily_check
        sequence:

          # Period due soon
          - if:
              - condition: template
                value_template: >
                  {{ enable_period_due and days_until == period_warning_days | int }}
            then:
              - service: "{{ notify_service }}"
                data:
                  title: "Period Due Soon"
                  message: >
                    {{ name_possessive }} period is predicted to start in
                    {{ days_until }} day{% if days_until != 1 %}s{% endif %}
                    ({{ states(next_period_sensor) }}).

          # PMS window — independent check, can fire same day as period-due
          - if:
              - condition: template
                value_template: >
                  {{ enable_pms_window and days_until >= 0 and days_until <= 5 }}
            then:
              - service: "{{ notify_service }}"
                data:
                  title: "PMS Window"
                  message: >
                    {% if days_until == 0 %}
                    {{ name_possessive }} period is expected today.
                    {% else %}
                    {{ name_subject }}
                    {{ "are" if name_subject in ["You", "They", "We"] else "is" }}
                    in {{ name_possessive | lower }} PMS window —
                    {{ days_until }} day{% if days_until != 1 %}s{% endif %} until {{ name_possessive | lower }} next period.
                    {% endif %}

          # Period start reminder — fires on the expected day and every day after
          # until the period is logged. Includes a "Log it now" action button.
          - if:
              - condition: template
                value_template: >
                  {{ enable_period_reminder and days_overdue >= 0
                     and not is_state(period_active_sensor, 'on') }}
            then:
              - service: "{{ notify_service }}"
                data:
                  title: >
                    {% if days_overdue == 0 %}
                    {{ name_possessive }} Period Is Due Today
                    {% else %}
                    {{ name_possessive }} Period Is {{ days_overdue }} Day{% if days_overdue != 1 %}s{% endif %} Late
                    {% endif %}
                  message: >
                    {% if days_overdue == 0 %}
                    {{ name_possessive }} period was predicted to start today.
                    {% else %}
                    {{ name_possessive }} period was predicted {{ days_overdue }}
                    day{% if days_overdue != 1 %}s{% endif %} ago and hasn't been logged yet.
                    {% endif %}
                    Did it start?
                  data:
                    actions:
                      - action: "{{ period_reminder_action_id }}"
                        title: "Log it now"

      # ── Period start confirmed via notification button ──────────────────────
      - conditions:
          - condition: trigger
            id: period_start_confirmed
        sequence:
          - service: menstrual_cycle_tracker.log_period_start
            data:
              tracker: "{{ tracker_for_service }}"
          - service: "{{ notify_service }}"
            data:
              title: "Period Logged"
              message: >
                {{ name_possessive }} period start has been logged for today.

mode: parallel
max: 5
